server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: turing123
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:xml/*.xml
